# Generated by Django 4.0.2 on 2022-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
    ]
