# Generated by Django 4.0.2 on 2022-02-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorml', '0008_alter_article_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='script',
            field=models.TextField(default='', verbose_name='Скрипт'),
            preserve_default=False,
        ),
    ]
