# Generated by Django 4.0.2 on 2022-02-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorml', '0010_alter_article_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='script',
        ),
    ]
