# Generated by Django 4.0.2 on 2022-03-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorml', '0011_remove_article_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
