# Generated by Django 4.0.2 on 2022-02-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorml', '0004_faq_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('notify_tutorials', models.BooleanField(default=False, verbose_name='Оповещать о туториалах')),
                ('notify_datasets', models.BooleanField(default=False, verbose_name='Оповещать о датасетах')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
