# Generated by Django 4.0.2 on 2022-02-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorml', '0007_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file_path',
            field=models.CharField(default='tutorml/img/blank.png', max_length=100, verbose_name='Путь к файлу'),
        ),
    ]
